server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG


spring:
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/spring_security
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true